# TCL File Generated by Component Editor 13.0sp1
# Sun Nov 02 13:51:15 COT 2014
# DO NOT MODIFY


# 
# sram_16bit_512k "SRAM_16Bit_512K" v1.0.2
#  2014.11.02.13:51:15
# 
# 

# 
# request TCL package from ACDS 13.1
# 
package require -exact qsys 13.1


# 
# module sram_16bit_512k
# 
set_module_property DESCRIPTION ""
set_module_property NAME sram_16bit_512k
set_module_property VERSION 1.0.2
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP "Terasic Technologies Inc"
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME SRAM_16Bit_512K
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property ANALYZE_HDL AUTO
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false


# 
# file sets
# 
add_fileset quartus_synth QUARTUS_SYNTH "" "Quartus Synthesis"
set_fileset_property quartus_synth TOP_LEVEL SRAM_16Bit_512K
set_fileset_property quartus_synth ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file SRAM_16Bit_512K.v VERILOG PATH hdl/SRAM_16Bit_512K.v TOP_LEVEL_FILE

add_fileset sim_verilog SIM_VERILOG "" "Verilog Simulation"
set_fileset_property sim_verilog TOP_LEVEL SRAM_16Bit_512K
set_fileset_property sim_verilog ENABLE_RELATIVE_INCLUDE_PATHS false
add_fileset_file SRAM_16Bit_512K.v VERILOG PATH hdl/SRAM_16Bit_512K.v TOP_LEVEL_FILE


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clk
# 
add_interface clk clock end
set_interface_property clk clockRate 0
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk iCLK clk Input 1


# 
# connection point avalon_slave_0_export
# 
add_interface avalon_slave_0_export conduit end
set_interface_property avalon_slave_0_export associatedClock ""
set_interface_property avalon_slave_0_export associatedReset ""
set_interface_property avalon_slave_0_export ENABLED true
set_interface_property avalon_slave_0_export EXPORT_OF ""
set_interface_property avalon_slave_0_export PORT_NAME_MAP ""
set_interface_property avalon_slave_0_export SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0_export SRAM_DQ export Bidir 16
add_interface_port avalon_slave_0_export SRAM_ADDR export Output 18
add_interface_port avalon_slave_0_export SRAM_UB_N export Output 1
add_interface_port avalon_slave_0_export SRAM_LB_N export Output 1
add_interface_port avalon_slave_0_export SRAM_WE_N export Output 1
add_interface_port avalon_slave_0_export SRAM_CE_N export Output 1
add_interface_port avalon_slave_0_export SRAM_OE_N export Output 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clk
set_interface_property avalon_slave_0 associatedReset reset_n
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 524288
set_interface_property avalon_slave_0 holdTime 20
set_interface_property avalon_slave_0 isMemoryDevice true
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitStates 20
set_interface_property avalon_slave_0 readWaitTime 20
set_interface_property avalon_slave_0 setupTime 20
set_interface_property avalon_slave_0 timingUnits Nanoseconds
set_interface_property avalon_slave_0 writeWaitStates 20
set_interface_property avalon_slave_0 writeWaitTime 20
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 iDATA writedata Input 16
add_interface_port avalon_slave_0 oDATA readdata Output 16
add_interface_port avalon_slave_0 iADDR address Input 18
add_interface_port avalon_slave_0 iWE_N write_n Input 1
add_interface_port avalon_slave_0 iOE_N read_n Input 1
add_interface_port avalon_slave_0 iCE_N chipselect_n Input 1
add_interface_port avalon_slave_0 iBE_N byteenable_n Input 2
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 1
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0


# 
# connection point reset_n
# 
add_interface reset_n reset end
set_interface_property reset_n associatedClock clk
set_interface_property reset_n synchronousEdges DEASSERT
set_interface_property reset_n ENABLED true
set_interface_property reset_n EXPORT_OF ""
set_interface_property reset_n PORT_NAME_MAP ""
set_interface_property reset_n SVD_ADDRESS_GROUP ""

add_interface_port reset_n iRST_N reset_n Input 1

